library/urls.py
from django.conf.urls import url
from . import views

app_name = 'library'
urlpatterns = [ 
    url(r'^$', views.index),
    url(r'^index', views.index, name='index'),
    url(r'^search$', views.search, name='search'),
    url(r'^classification$', views.classification, name='classification'),
    url(r'^book_detail', views.book_detail, name='book_detail'),
]

user/urls.py
from django.conf.urls import url
from . import views

app_name = "user"
urlpatterns = [
    url(r'^user', views.user, name='user'),
    url(r'^login$', views.login, name='login'),
    url(r'^favorite', views.favorite, name='favorite'),
    url(r'^borrow_column', views.borrow_column, name='borrow_column'),
    url(r'^backbook', views.backbook, name='backbook'),
    url(r'^order', views.order, name='order'),
    url(r'^information', views.information, name='information'),
]

weixin/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^basic/', include('basic.urls')),
    url(r'^library/', include('library.urls')),
    url(r'^user/', include('user.urls')),
    url(r'^manager/', include('manager.urls')),
]

library/models.py
from django.db import models

class User(models.Model):
	name = models.CharField(max_length=100)
	passwd = models.CharField(max_length=30)
	mobile = models.CharField(max_length=30)
	books = models.TextField(default='', blank=True)
	borrow_column = models.TextField(default='', blank=True)
	favorite = models.TextField(default='', blank=True)
	Type = models.CharField(max_length=10, default = '', blank=True)

	openid = models.CharField(max_length=100, default='', blank=True)
	nickname = models.CharField(max_length=100, default='', blank=True)
	sex = models.CharField(max_length=100, default='', blank=True)
	language = models.CharField(max_length=100, default='', blank=True)
	city = models.CharField(max_length=100, default='', blank=True)
	province = models.CharField(max_length=100, default='', blank=True)
	country = models.CharField(max_length=100, default='', blank=True)
	headimgurl = models.CharField(max_length=300, default='', blank=True)
	privilege = models.CharField(max_length=100, default='', blank=True)

class Book(models.Model):
	name = models.CharField(max_length=100)
	type_id = models.ForeignKey('Book_type', on_delete=models.CASCADE)
	author = models.CharField(max_length=100, default="unknown")
	version = models.CharField(max_length=10, blank=True)
	image = models.CharField(max_length=100, blank=True)
	inventory = models.SmallIntegerField(default=0)      # 库存
	public = models.CharField(max_length=100, default="unknown")
	public_time = models.DateField(auto_now=True)
	page_num = models.SmallIntegerField(blank=True, default=0)
	price = models.FloatField(default=0)
	ISBN = models.CharField(max_length=20, default="unknown")

	content_abstract = models.TextField(blank=True)
	author_abstract = models.TextField(blank=True)
	directory = models.TextField(blank=True)
	review = models.TextField(blank=True)

	Users = models.CharField(max_length=200, default='', blank=True)

class Book_type(models.Model):
	name = models.CharField('书名', max_length=30)
	note = models.CharField(max_length=30, blank=True)
	top_type = models.ForeignKey('Book_type', on_delete=models.CASCADE, blank=True)

	def __str__(self):
		return self.name

library/views.py
from django.shortcuts import render, reverse
from django.http import HttpResponse, HttpResponseRedirect
from django.db import connection
from random import random
from urllib.parse import quote
from .models import Book_type, User, Book

def index(request):
	books = Book.objects.all()
	data = {"books": books}
	return render(request, 'library/index.html', data)

def classification(request):
	if request.GET.get('id'):
		t = Book_type.objects.get(id=request.GET['id'])
		books = t.book_set.all()
		data = {'books': books, 'class': t}
	else:
		classes = Book_type.objects.all()
		data = {'classes': [x for x in classes if not bool(x.top_type_id)]}
	return render(request, 'library/classification.html', data)
	
def search(request):
	if request.POST.get('search'):
		books = Book.objects.filter(name__contains=request.POST['search'].strip())
		if len(books) == 0:
			data = {'error': True}
		else:
			data = {"books": books}
		return render(request, 'library/search.html', data)
	else:
		return render(request, 'library/search.html')

def book_detail(request):
	book = Book.objects.get(id=request.GET['id'])
	about = list(book.type_id.book_set.all())
	favorite = 1 if str(request.GET['id']) in User.objects.get(id=request.session['id']).favorite else 0
	data = {'book': book, 'about': about, 'favorite':favorite }
	return render(request, 'library/book_detail.html', data)

user/views.py
from django.shortcuts import render, reverse
from django.http import HttpResponse, HttpResponseRedirect
from django.db import connection
from library.models import *
import os

def login(request):
	if request.method == "POST":
		user = User.objects.get(mobile=request.POST['mobile']);
		if user.passwd == request.POST['password']:
			request.session['id'] = user.id
			request.session['name'] = user.name if len(user.name) else user.nickname
			request.session['openid'] = user.openid
			request.session['img'] = user.headimgurl
			if user.Type == "manager":
				request.session['Type'] = 'manager'
				return HttpResponseRedirect(reverse('manager:user'))
			return HttpResponseRedirect(reverse('user:user'))
		else:
			return render(request, 'user/login.html', {'error': 'error'})
	else:
		return render(request, 'user/login.html')

def user(request):
	if request.session.get('name', False):
		data = {'name': request.session.get('name'), 'image': request.session.get('img')}
		return render(request, 'user/user.html', data)
	else:
		return render(request, 'user/login.html')

def information(request):
	user = User.objects.get(id=request.session.get('id'))
	data = dict()
	if request.method == "POST":
		user.name = request.POST['name']
		user.sex = 2 if request.POST.get('sex') else 1

		# save headimage
		try:
			file = request.FILES.get('headimgurl')
			file_name = str(request.session['id']) + '.jpg'
			file_url = os.path.join(os.path.dirname(os.path.dirname(os.path.abspath(__file__))) + '/static/images/headimg/', file_name)
			with open(file_url, 'wb') as f:
				f.write(file.read())
			user.headimgurl = '/static/images/headimg/' + file_name
		except:
			pass

		user.save()
		request.session['img'] = user.headimgurl
		request.session['name'] = user.name
		data['change'] = 'true'

	data["user"] = user
	return render(request, 'user/information.html', data)

def favorite(request):
	if request.session.get('name'):
		if request.GET.get('id'):
			with connection.cursor() as cursor:
				cursor.execute("update library_user set favorite = concat(favorite, '%s ') where id = %s" % (request.GET['id'], request.session['id']))
			return HttpResponseRedirect("/library/book_detail?id=%s" % request.GET['id'])
		else:
			favorite_book = User.objects.get(id=request.session['id']).favorite.split()
			books = Book.objects.filter(id__in=favorite_book)
			data = {'books':books}
			return render(request, 'user/favorite.html', data)
	else:
		return HttpResponseRedirect(reverse("user:login"))

def borrow_column(request):
	if request.GET.get('id'):
		with connection.cursor() as cursor:
			cursor.execute("update library_user set borrow_column = concat(borrow_column, '%s ') where id = %s" % (request.GET['id'], request.session['id']))
		return HttpResponseRedirect(reverse('library:borrow_column'))
	else:
		borrow_column_book = User.objects.get(id=request.session['id']).borrow_column.split()
		# return HttpResponse(borrow_column_book)
		books = Book.objects.filter(id__in=borrow_column_book)
		data = {'books':books}
		return render(request, 'user/borrow_column.html', data)

# show borrowed book
def borrowed(request):
	books = Book.objects.filter(id__in = User.objects.get(id=request.session['id']).books.split())
	data = {'books': books}
	return render(request, 'user/borrowed.html')

def backbook(request):
	books = User.objects.get(id=request.session.get('id')).books.split();
	books = Book.objects.filter(id__in = books)
	data = {'books': books}
	return render(request, 'user/backbook.html', data)

def order(request):
	return render(request, 'basic/error.html')

templates/library/base.html
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="utf-8">
	<title>{% block title %} 阅读伴侣 {% endblock %}</title>
	<meta name="viewport" content="initial-scale=1, maximum-scale=1">
	<link rel="stylesheet" href="http://m.sui.taobao.org/dist/css/sm.css">
	<script src="http://m.sui.taobao.org/assets/js/zepto.js"></script>
	<script src="http://m.sui.taobao.org/dist/js/sm.js"></script>

	<!-- 三列显示书籍样式 -->
	<style>
		.books img{
			width: 100%;
		}
		.books a {
			text-decoration: none;
			text-align: center;
		}
	</style>

	{% block head %} {% endblock %}
</head>
<body>
	<div class="page-group">
		<div class="page">
			<header class="bar bar-nav">
				{% block header %}
				<a class="button button-link button-nav icon icon-left pull-left back"></a>
				<a class="icon icon-refresh pull-right" onclick="location.reload();"></a>
  				{% endblock %}
				<h1 class="title">阅读伴侣</h1>
			</header>

			<nav class="bar bar-tab">
				<a class="tab-item external" href="{% url 'library:index' %}">
					<span class="icon icon-home"></span>
					<span class="tab-label">书 城</span>
				</a>
				<a class="tab-item external" href="{% url 'library:classification' %}">
					<span class="icon icon-app"></span>
					<span class="tab-label">分 类</span>
				</a>
				<a class="tab-item external" href="{% url 'user:user' %}">
					<span class="icon icon-me"></span>
					<span class="tab-label">我 的</span>
				</a>
			</nav>

			<div class="content content-padded">
				{% block main %} {% endblock %}
			</div>
		</div>
	</div>

	{% block other %} {% endblock %}

	<script>$.init();</script>
</body>
</html>

templates/library/book_detail.html
{% extends 'library/base.html' %}
{% block title %} {{book.name}} {% endblock %}
{% block head %}
<style>
	.button-link {
		font-size: 0.8rem;
		line-height: 2.2rem;
		height: 2.2rem;
		color: #0894ec;
	}
	.info .book_image {
		width: 40%;
	}
	.info .detail{
		position: relative;
		top: -255px;
		left: 50%;
		font: 12px Helvetica,Arial,sans-serif;
	}
	.info span {
		color: #666;
		font: 12px Arial, Helvetica, sans-serif;;
	}
	.info .order {
		position: relative;
		top: -255px;
	}
	.info {
		margin-bottom: -255px;
	}

	.book_content p{
		text-indent: 2em;
	}
	h3 {
		color: #007722;
	}

</style>
{% endblock %}

{% block header %}
	<a class="button button-link button-nav icon icon-left pull-left back"></a>
	<a class="button button-link icon icon-star pull-right" href="{% url 'user:favorite' %}?id={{book.id}}">
	{% ifequal favorite '1' %}
		<a class="button button-link icon icon-star pull-right" href="#" onclick="alert('已收藏');">
		<span class="badge">已收藏</span></a>
	{% endifequal %}
	{% ifequal favorite '0' %}
		<a class="button button-link icon icon-star pull-right" href="{% url 'user:favorite' %}?id={{book.id}}"></a>
	{% endifequal %}
{% endblock %}

{% block main%}
	<div class="info">
		<img src="{{book.image}}" class="book_image">
		<div class="detail">
			<p><span>所属分类</span>: {{book.type_id.name}}</p>
			<p><span>作者</span>: {{book.author}} </p>
			<p><span>版本号</span>: {{book.version}}</p>
			<p><span>库存</span>: {{book.inventory}} </p>
			<p><span>出版社</span>: {{book.public}}</p>
			<p><span>出版时间</span>: {{book.public_time}}</p>
			<p><span>页数</span>: {{book.page_num}}</p>
			<p><span>压金</span>: {{book.price}} 元</p>
			<p><span>ISBN</span>: 9787559400574</p>
		</div>

		<a href="{% url 'user:order' %}?id={{book.id}}" class="button order">预订</a>
	</div>

		<div class="book_content">
			<h3>内容简介  · · · · · ·</h3>
			<p> {{book.content_abstract}} </p>

			<h3>作者简介  · · · · · ·</h3>
			<p> {{book.author_abstract}} </p>

			<h3>目录  · · · · · ·</h3>
			<p> {{book.directory}} </p>

			<h3>书评</h3>
			<p> {{book.review}} </p>
		</div>

	<hr />

	<div class="recommended">
		<h3>相关书籍</h3>
		<div class="row books">

			{% for book in about %}
			<div class="col-33">
				<img src="{{book.image}}" />
				<a href="{% url 'library:book_detail' %}?id={{book.id}}">{{book.name}}</a>
				<p>{{book.author}}</p>
			</div>
			{% endfor %}
			
		</div>
	</div>
{% endblock %}

templates/library/classification.html
{% extends 'library/base.html' %}
{% block title %} 分类检索 {% endblock %}
{% block head %}
<style>
	h2 {
		text-align: center;
	}
	.center-block-title {
		margin: 10px 0 -30px 0;
	}
</style>
{% endblock %}

{% block header %}
	<a class="button button-link button-nav icon icon-left pull-left back"></a>
	<a href="{% url 'library:search' %}" class="icon icon-search pull-right"></a>
{% endblock %}

{% block main %}
	{% if classes %}
		<h2>书籍分类</h2>
		{% for class in classes %}
		<div class="center-block-title">{{ class.name }}</div>
		<div class="list-block">
			<ul>
				{% for sub in class.book_type_set.all %}
				<a href="{% url 'library:classification' %}?id={{sub.id}}"><li class="item-content item-link">
					<div class="item-inner">
						<div class="item-title">{{ sub.name }}</div>
					</div>
				</li></a>
				{% endfor %}
			</ul>
		</div>
		{% endfor %}

	{% else %}
	<h2>{{class.name}}</h2>
	<div class="row books">

		{% for book in books %}
		<div class="col-33">
			<img src="{{book.image}}" class="book-name">
			<a href="{% url 'library:book_detail' %}?id={{book.id}}">{{ book.name }}</a>
			<p class="book-writer">{{ book.author }}</p>
		</div>
		{% endfor %}
	</div>
	{% endif %}
{% endblock %}

templates/library/index.html
{% extends 'library/base.html' %}
{% block title %} 书城 {% endblock %}

{% block header %}
	<a class="icon icon-back pull-left"></a>
	<a href="{% url 'library:search' %}" class="icon icon-search pull-right"></a>
{% endblock %}

{% block main %}

	<div class="grid-demo books">
		<div class="row">
			{% for book in books %}
			<div class="col-33">
			<img src="{{book.image}}" class="book-name">
			<a href="{% url 'library:book_detail' %}?id={{book.id}}">{{ book.name }}</a>
			<p class="book-writer">{{ book.author }}</p>
		</div>
			{% endfor %}
		</div>
	</div>

{% endblock %}

templates/library/search.html
{% extends 'library/base.html' %}
{% block title %} 搜索 {% endblock %}
{% block head %}
<style>
	.books .ui-block-a {
		margin-left: -20px;
	}
	.books img{
		width: 100%;
		height: 138px;
	}
	.books a {
		text-decoration: none;
		text-align: center;
	}
	.error {
		text-align: center;
		color: #bbb;
	}
</style>

<script>
	function submit() {
		document.getElementById("form").submit();
	}
</script>
{% endblock %}

{% block header %}
	<a class="button button-link button-nav icon icon-left pull-left back"></a>
{% endblock %}

{% block main %}
	<form method="post" action="{% url 'library:search' %}" id="form">
		{% csrf_token %}
		<div class="searchbar row">
			<div class="search-input col-85">
				<input type="search" id="search" placeholder="输入关键字..." name="search">
			</div>
		<a class="button button-fill button-primary col-15" onclick="submit();"><span class="icon icon-search"></span></a>
		</div>
	</form>

	{% if books %}
	<div class="grid-demo">
		<div class="row books">
			{% for book in books %}
			<div class="col-33">
			<img src="{{book.image}}" class="book-name">
			<a href="{% url 'library:book_detail' %}?id={{book.id}}">{{ book.name }}</a>
			<p class="book-writer">{{ book.author }}</p>
		</div>
			{% endfor %}
		</div>
	</div>
	{% endif %}

	{% if error %}
		<p class="error">暂无结果</p>
	{% endif %}
{% endblock %}

templates/library/user.html
{% extends 'library/base.html' %}
{% block title %} 个人中心 {% endblock %}
{% block style %}
<style>
	.user-info p{
		text-align: center;
	}
	.user-info img {
		border-radius:60px; 
	}

	.gray {
		width: 100%;
		height: 10px;
		background: #ddd;
	}

	.ui-listview, .ui-panel-inner>.ui-listview {
		margin: 1em 0em !important;
	}

	.ui-page-theme-a .ui-btn, html .ui-bar-a .ui-btn, html .ui-body-a .ui-btn, html body .ui-group-theme-a .ui-btn, html head+body .ui-btn.ui-btn-a, .ui-page-theme-a .ui-btn:visited, html .ui-bar-a .ui-btn:visited, html .ui-body-a .ui-btn:visited, html body .ui-group-theme-a .ui-btn:visited, html head+body .ui-btn.ui-btn-a:visited {
		background: #fff;
	}
</style>
{% endblock %}

{% block main %}
{% load static %}
	<div class="user-info">
		<p><img src="{{ image }}" class="ui-response"><p>
		<p>{{ name }}</p>
	</div>

	<!-- <div class="gray"></div> -->

	<div class="abc">
		<ul data-role="listview">
			<li><a href="#">个人资料</a></li>
		</ul>

		<ul data-role="listview">
			<li><a href="{% url 'library:borrow_column' %}">借书栏</a></li>
			<li><a href="#">预订</a></li>
			<li><a href="#">收藏</a></li>
			<li><a href="#">借阅历史</a></li>
		</ul>

		<!-- <div class="gray"></div> -->

		<ul data-role="listview">
			<li><a href="#">还书</a></li>
		</ul>
	</div>


{% endblock %}