user/urls.py
from django.conf.urls import url
from . import views

app_name = "user"
urlpatterns = [
    url(r'^user', views.user, name='user'),
    url(r'^login$', views.login, name='login'),
    url(r'^favorite', views.favorite, name='favorite'),
    url(r'^borrow_column', views.borrow_column, name='borrow_column'),
    url(r'^backbook', views.backbook, name='backbook'),
    url(r'^order', views.order, name='order'),
    url(r'^information', views.information, name='information'),
]

weixin/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^basic/', include('basic.urls')),
    url(r'^library/', include('library.urls')),
    url(r'^user/', include('user.urls')),
    url(r'^manager/', include('manager.urls')),
]

user/views.py
from django.shortcuts import render, reverse
from django.http import HttpResponse, HttpResponseRedirect
from django.db import connection
from library.models import *
import os

def login(request):
	if request.method == "POST":
		user = User.objects.get(mobile=request.POST['mobile']);
		if user.passwd == request.POST['password']:
			request.session['id'] = user.id
			request.session['name'] = user.name if len(user.name) else user.nickname
			request.session['openid'] = user.openid
			request.session['img'] = user.headimgurl
			if user.Type == "manager":
				request.session['Type'] = 'manager'
				return HttpResponseRedirect(reverse('manager:user'))
			return HttpResponseRedirect(reverse('user:user'))
		else:
			return render(request, 'user/login.html', {'error': 'error'})
	else:
		return render(request, 'user/login.html')

def user(request):
	if request.session.get('name', False):
		data = {'name': request.session.get('name'), 'image': request.session.get('img')}
		return render(request, 'user/user.html', data)
	else:
		return render(request, 'user/login.html')

def information(request):
	user = User.objects.get(id=request.session.get('id'))
	data = dict()
	if request.method == "POST":
		user.name = request.POST['name']
		user.sex = 2 if request.POST.get('sex') else 1

		# save headimage
		try:
			file = request.FILES.get('headimgurl')
			file_name = str(request.session['id']) + '.jpg'
			file_url = os.path.join(os.path.dirname(os.path.dirname(os.path.abspath(__file__))) + '/static/images/headimg/', file_name)
			with open(file_url, 'wb') as f:
				f.write(file.read())
			user.headimgurl = '/static/images/headimg/' + file_name
		except:
			pass

		user.save()
		request.session['img'] = user.headimgurl
		request.session['name'] = user.name
		data['change'] = 'true'

	data["user"] = user
	return render(request, 'user/information.html', data)

def favorite(request):
	if request.session.get('name'):
		if request.GET.get('id'):
			with connection.cursor() as cursor:
				cursor.execute("update library_user set favorite = concat(favorite, '%s ') where id = %s" % (request.GET['id'], request.session['id']))
			return HttpResponseRedirect("/library/book_detail?id=%s" % request.GET['id'])
		else:
			favorite_book = User.objects.get(id=request.session['id']).favorite.split()
			books = Book.objects.filter(id__in=favorite_book)
			data = {'books':books}
			return render(request, 'user/favorite.html', data)
	else:
		return HttpResponseRedirect(reverse("user:login"))

def borrow_column(request):
	if request.GET.get('id'):
		with connection.cursor() as cursor:
			cursor.execute("update library_user set borrow_column = concat(borrow_column, '%s ') where id = %s" % (request.GET['id'], request.session['id']))
		return HttpResponseRedirect(reverse('library:borrow_column'))
	else:
		borrow_column_book = User.objects.get(id=request.session['id']).borrow_column.split()
		# return HttpResponse(borrow_column_book)
		books = Book.objects.filter(id__in=borrow_column_book)
		data = {'books':books}
		return render(request, 'user/borrow_column.html', data)

# show borrowed book
def borrowed(request):
	books = Book.objects.filter(id__in = User.objects.get(id=request.session['id']).books.split())
	data = {'books': books}
	return render(request, 'user/borrowed.html')

def backbook(request):
	books = User.objects.get(id=request.session.get('id')).books.split();
	books = Book.objects.filter(id__in = books)
	data = {'books': books}
	return render(request, 'user/backbook.html', data)

def order(request):
	return render(request, 'basic/error.html')

templates/user/backbook.html
{% extends 'library/base.html' %}
{% block title %} 还书 {% endblock %}
{% block head %}
<script src="http://libs.baidu.com/jquery/2.0.0/jquery.min.js"></script>
<style>
	.booklist {
		padding: 1em;
		background: #fff;
		height: 120px;
		border-bottom: 10px solid #f9f9f9;
	}
	h1 {
		margin: 10px 0;
	}
	img {
		width: 20%;
	}
	h3, h4{
		position: relative;
		top: -100px;
		left: 25%;
	}
	.QR {
		position: relative;
		top: -220px;
		left: 70%;
		width: 30%;
	}
	.QR_1 {
		background: #f00;
		position: absolute;
		top: 100px;
		left: 5%;
		width: 90%;
		height: auto;
		padding-bottom: 20px;
	}
	.QR_1 img {
		width: 100%;
	}
	#closeQR {
		width: 50%;
		height: 30px;
	}
</style>

<script type="text/javascript">
	$(document).ready(function() {
		$("div.QR_1").hide();
		$("#closeQR").click(function() {
			$("div.QR_1").fadeOut();
		});
	});
	function scan(src) {
		$("img#QRCode").attr('src', src);
		$("div.QR_1").css('background-color', '#fff');
		$("div.QR_1").fadeIn();
	};

</script>
{% endblock %}

{% block main %}
{% load static %}

	<center><h1>已借书籍</h1></center>
	{% for book in books %}
	<div class="booklist">
		<img src="{{ book.image }}"/>
		<h3>{{ book.name }}</h3>
		<h4>{{ book.author }}</h4>
		<img src="{% static 'images/QR.jpg' %}" class="QR" onclick="scan(this.src);"></a>
	</div>
	{% endfor %}

	<div class="QR_1">
		<img src="" id="QRCode">
		<center><button class="button button-round" id="closeQR">关闭</button></center>
	</div>
{% endblock %}

templates/user/borrow_column.html
{% extends 'library/base.html' %}
{% block title %} 借书栏 {% endblock %}
{% block head %}
<script src="http://libs.baidu.com/jquery/2.0.0/jquery.min.js"></script>
<style>
	.booklist {
		padding: 1em;
		background: #fff;
		height: 120px;
		border-bottom: 10px solid #f9f9f9;
	}
	h1 {
		margin: 10px 0;
	}
	img {
		width: 20%;
	}
	h3, h4{
		position: relative;
		top: -100px;
		left: 25%;
	}
	.QR {
		position: relative;
		top: -220px;
		left: 70%;
		width: 30%;
	}
	.QR_1 {
		background: #f00;
		position: absolute;
		top: 100px;
		left: 5%;
		width: 90%;
		height: auto;
		padding-bottom: 20px;
	}
	.QR_1 img {
		width: 100%;
	}
	#closeQR {
		width: 50%;
		height: 30px;
	}
</style>

<script type="text/javascript">
	$(document).ready(function() {
		$("div.QR_1").hide();
		$("#closeQR").click(function() {
			$("div.QR_1").fadeOut();
		});
	});
	function scan(src) {
		$("img#QRCode").attr('src', src);
		$("div.QR_1").css('background-color', '#fff');
		$("div.QR_1").fadeIn();
	};

</script>
{% endblock %}

{% block main %}
{% load static %}

	<center><h1>借书栏</h1></center>
	{% for book in books %}
	<div class="booklist">
		<img src="{{ book.image }}"/>
		<h3>{{ book.name }}</h3>
		<h4>{{ book.author }}</h4>
		<img src="{% static 'images/QR.jpg' %}" class="QR" onclick="scan(this.src);"></a>
	</div>
	{% endfor %}

	<div class="QR_1">
		<img src="" id="QRCode">
		<center><button class="button button-round" id="closeQR">关闭</button></center>
	</div>
{% endblock %}

templates/user/borrowed.html
{% extends 'library/base.html' %}
{% block title %} 借书栏 {% endblock %}
{% block style %}
<style>
	.booklist {
		padding: 1em;
		background: #fff;
		height: 120px;
		border-bottom: 10px solid #f9f9f9;
	}
	img {
		width: 20%;
	}
	h3, h4{
		position: relative;
		top: -100px;
		left: 25%;
	}
	.QR {
		position: relative;
		top: -220px;
		left: 70%;
		width: 30%;
	}
	.QR_1 {
		width: 100%;
	}
</style>

<script type="text/javascript">
	$("img.QR").onclick(function () {
		$("img.QR_1").attr('src', $(this).src);
		alert($(this).src);
	})
</script>
{% endblock %}

{% block main %}
{% load static %}

	<center><h1>已借图书</h1></center>
	{% for book in books %}
	<div class="booklist">
		<img src="{{ book.image }}"/>
		<h3>{{ book.name }}</h3>
		<h4>{{ book.author }}</h4>
		<a href="#myPopup" data-rel="popup" data-position-to="window">
    <img src="{% static 'images/QR.jpg' %}" class="QR"></a>
	</div>
	{% endfor %}

	<div data-role="popup" id="myPopup">
      <a href="#pageone" data-rel="back" class="ui-btn ui-corner-all ui-shadow ui-btn-a ui-icon-delete ui-btn-icon-notext ui-btn-right">Close</a><img src="{% static 'images/QR.jpg' %}" class="QR_1" alt="Skaret View">
    </div>
{% endblock %}

templates/user/favorite.html
{% extends 'library/base.html' %}
{% block title %} 收藏夹 {% endblock %}
{% block head %}
<script src="http://libs.baidu.com/jquery/2.0.0/jquery.min.js"></script>
<style>
	.booklist {
		padding: 1em;
		background: #fff;
		height: 120px;
		border-bottom: 10px solid #f9f9f9;
	}
	.booklist .detail {
		position: relative;
		top: -120%;
		left: 30%;
	}
	h3 {
		margin: 0;
	}
	.detail span {
		color: red;
	}
	h1 {
		margin: 10px 0;
	}
	img {
		width: 20%;
	}
</style>
{% endblock %}

{% block main %}
{% load static %}

	<center><h1>收藏夹</h1></center>
	{% for book in books %}
	<div class="booklist">
		<img src="{{ book.image }}"/>
		<div class="detail">
			<h3>{{ book.name }}</h3>
			<small>{{ book.author }}</small> <br />
			<small>现有本<span> {{ book.inventory }} </span>未借出</small>
		</div>
	</div>
	{% endfor %}
{% endblock %}

templates/user/information.html
{% extends 'library/base.html' %}
{% block title %} 个人资料 {% endblock %}
{% block head %}
	<script>
		{% if change %}
		window.onload = function() {
			alert("修改成功");
		};
		{% endif %}
	</script>

	<style>
		img {
			width: 40%;
			margin: 10px 10%;
			display: block;
			height: auto;
			border-radius: 50%;
		}
	</style>
{% endblock %}

{% block main %}
	<form method="post" action="{% url 'user:information' %}" enctype="multipart/form-data">
	{% csrf_token %}
	<div class="list-block"><ul>
		<li><div class="item-content">
			<div class="item-inner">
				<div class="item-title label">昵称</div>
				<div class="item-input">
					<input type="text" name="name" value="{{user.name}}">
				</div>
			</div>
		</div></li>
		
		<li><div class="item-content">
			<div class="item-inner">
				<div class="item-title label">性别</div>
				<div class="item-input">
					帅哥 &nbsp;
					<label class="label-switch">
						<input type="checkbox" name="sex" {% ifequal user.sex '2' %} checked {% endifequal %}>
						<div class="checkbox"></div>
					</label>
					&nbsp; 美女
				</div>
			</div>
		</div></li>

		<li><div class="item-content">
			<div class="item-inner">
				<div class="item-title label">头像</div>
				<div class="item-input">
					<img src="{{user.headimgurl}}" />
					<input type="file" name="headimgurl" style="margin-bottom: 10px;">
				</div>
			</div>
		</div></li>
	</ul></div>

		<div class="content-block">
			<input type="submit" name="submit" value="修改" class="button button-fill button-big button-success">
		</div>
	</form>
{% endblock %}

templates/user/login.html
{% extends 'library/base.html' %}
{% block title %}登录{% endblock %}
{% block head %}
<style>
	.logo {
		border-radius: 90px;
		width: 40%;
		height: auto;
		margin: 0 0 -20px 30%;
	}

	.error {
		color: red;
		text-align: center;
	}

	.submit {
		margin-top: 20px;
	}

	.weixin {
		position: absolute;
		bottom: 0px;
		width: 100%;
		color: #aaa;
		margin-bottom: -15px;
	}
	.weixin img{
		width: 20%;
	}
	.weixin a {
		margin-left: 40%;
	}
	.weixin p {
		margin-top: 5px;
	}
</style>
{% endblock %}

{% block main %}
	<img src="https://ss1.bdstatic.com/70cFvXSh_Q1YnxGkpoWK1HF6hhy/it/u=4003502413,4072842394&fm=26&gp=0.jpg" class="logo">

	{% if error %}
		<p class="error">用户名或密码错误</p>
	{% endif %}

	<form method="post" action="{% url 'user:login' %}">
	{% csrf_token %}
	<div class="list-block">
	<ul>
		<li><div class="item-content">
			<div class="item-inner">
				<div class="item-title label">手机号</div>
				<div class="item-input">
					<input type="text" name="mobile" placeholder="手机号">
				</div>
			</div>
		</div></li>

		<li><div class="item-content">
			<div class="item-inner">
				<div class="item-title label">密码</div>
				<div class="item-input">
					<input type="password" name="password" placeholder="密码">
				</div>
			</div>
		</div></li>
	</ul>
		<div class="center-block">
			<input type="submit" name="submit" value="登录" class="button button-big button-success button-fill submit">
		</div>
	</form>
	
	<div class="weixin">
		<hr />
		<a href="https://open.weixin.qq.com/connect/oauth2/authorize?appid=wx2fab5d8fc63cdcee&redirect_uri=http%3a%2f%2fwww.unihyj.cn%2fbasic%2flogin&response_type=code&scope=snsapi_userinfo&state=STATE&connect_redirect=1#wechat_redirect"><img src="https://ss1.baidu.com/6ONXsjip0QIZ8tyhnq/it/u=1744032013,2517964115&fm=58" class="img-responsive center-block img-rounded"/></a>
		<p class="text-center">使用微信登录</p>
	</div>
{% endblock %}

templates/user/user.html
{% extends 'library/base.html' %}
{% block title %} 个人中心 {% endblock %}
{% block head %}
<style>
	.user-info p{
		text-align: center;
	}
	.user-info .name {
		margin: -10px 0;
	}
	.user-info img {
		display: block;
		width: 40%;
		margin-left: 30%;
		height: auto;
		border-radius: 50%;
	}

	.gray {
		width: 100%;
		height: 10px;
		background: #ddd;
	}
	.list-block ul {
		margin: 10px 0;
	}
</style>
{% endblock %}

{% block main %}
	<div class="user-info">
		<p><img src="{{image}}" class="item-content item-link"></p>
		<p>{{name}}</p>

		<div class="list-block">
		<ul><li>
			<div class="item-content item-link">
				<div class="item-inner">
					<a href="{% url 'user:information' %}"><div class="item-title">个人资料</div></a>
				</div>
			</div>
		</li></ul>

		<ul>
			<li class="item-content item-link">
				<div class="item-inner">
					<a href="{% url 'user:borrow_column' %}"><div class="item-title">借书栏</div></a>
				</div>
			</li>
			<li class="item-content item-link">
				<div class="item-inner">
					<div class="item-title">预订</div>
				</div>
			</li>
			<li class="item-content item-link">
				<div class="item-inner">
					<a href="{% url 'user:favorite' %}"><div class="item-title">收藏</div></a>
				</div>
			</li>
		</ul>

		<ul><li class="item-content item-link">
			<div class="item-inner">
				<a href="{% url 'user:backbook' %}"><div class="item-title"> 还书 </div></a>
			</div>
		</li></ul>
		</div>
	</div>
{% endblock %}